In [29]:
import numpy as np
import pandas as pd

#  1 Sulipdykite iš 4 fragmentų vieną lentelę:
* top_left = pd.read_csv('top1-25-1.csv')
* top_right = pd.read_csv('top1-25-2.csv')
* bottom_left = pd.read_csv('top26-50-1.csv')
* bottom_right = pd.read_csv('top26-50-2.csv')

pirmiausiai sujunkite apatinę dalį, tada viršutinę *(yra persidengiančių stulpelių!)*, galiausiai viršų su apačia. Naudokite **.concat()** ir **.merge()** metodus.

In [139]:
top_left = pd.read_csv('top1-25-1.csv')
top_right = pd.read_csv('top1-25-2.csv')
bottom_left = pd.read_csv('top26-50-1.csv')
bottom_right = pd.read_csv('top26-50-2.csv')
data_bottom = pd.concat([bottom_left, bottom_right], axis=1)
data_top = pd.merge(top_left, top_right, on=['Track.Name', 'Popularity'])
data = pd.concat([data_top, data_bottom], sort=False)

In [140]:
data.head()

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
0,Senorita,Shawn Mendes,canadian pop,79.0,117,55,76,-6,8,75,191,4,3
1,China,Anuel AA,reggaeton flow,92.0,105,81,79,-4,8,61,302,8,9
2,boyfriend (with Social House),Ariana Grande,dance pop,85.0,190,80,40,-4,16,70,186,12,46
3,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
4,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,94.0,150,65,58,-4,11,18,175,45,7

# 2 Sutvarkykite indeksą - padarykite, kad prasidėtų nuo 1.

In [141]:
data['#'] = list(range(1, 51))

In [142]:
data.set_index('#', inplace=True)

In [143]:
data.head()

,Track.Name,Artist.Name,Genre,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
#,,,,,,,,,,,,,
1,Senorita,Shawn Mendes,canadian pop,79.0,117,55,76,-6,8,75,191,4,3
2,China,Anuel AA,reggaeton flow,92.0,105,81,79,-4,8,61,302,8,9
3,boyfriend (with Social House),Ariana Grande,dance pop,85.0,190,80,40,-4,16,70,186,12,46
4,Beautiful People (feat. Khalid),Ed Sheeran,pop,NaN,93,65,64,-8,8,55,198,12,19
5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,94.0,150,65,58,-4,11,18,175,45,7

# 3 Sukurkite grupavimo pagal žanrą objektą

In [144]:
grouped = data.groupby('Genre')

In [145]:
grouped

# 4 kokie žanrai lentelėje pasitaiko daugiau negu 3 kartus?

In [146]:
newdf = grouped.count()

In [147]:
newdf.head()

,Track.Name,Artist.Name,Popularity,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.
Genre,,,,,,,,,,,,
atl hip hop,1,1,1,1,1,1,1,1,1,1,1,1
australian pop,1,1,1,1,1,1,1,1,1,1,1,1
big room,1,1,1,1,1,1,1,1,1,1,1,1
boy band,1,1,1,1,1,1,1,1,1,1,1,1
brostep,2,2,1,2,2,2,2,2,2,2,2,2

In [87]:
newdf[newdf['Energy']>3]['Energy']

Genre
dance pop    8
latin        5
pop          6
Name: Energy, dtype: int64

# 5 Koks žanras pats populiariausias? Koks mažiausiai populiarus?
(pagal populiarumo vidurkį)

In [148]:
most_popular_genre = grouped.mean()['Popularity'].idxmax()
most_popular_score = grouped.mean()['Popularity'].max()
least_popular_genre = grouped.mean()['Popularity'].idxmin()
least_popular_score = grouped.mean()['Popularity'].min()
print(most_popular_genre, most_popular_score)
print(least_popular_genre, least_popular_score)

electropop 95.0
canadian pop 74.5

# 6 Sukurkite lentelę, kurioje matytųsi, koks žanras turi aukščiausią vidurkį kiekviename rodiklyje, bei pats vidurkis.

In [151]:
indikatoriai = data.columns.tolist()[3:]
zanrai = grouped.mean()[cols].idxmax()
skaiciai = grouped.mean()[cols].max()
result = pd.DataFrame([indikatoriai, zanrai, skaiciai], 
                      ['Indikatorius', 'Žanras', 'Balai']).transpose()

In [152]:
result

       Indikatorius          Žanras  Balai
0        Popularity      electropop     95
1  Beats.Per.Minute      trap music    180
2            Energy  reggaeton flow     80
3      Danceability  r&b en espanol     88
4    Loudness..dB..         brostep   -2.5
5          Liveness         brostep   37.5
6          Valence.        boy band     95
7           Length.  reggaeton flow  305.5
8    Acousticness..  australian pop     69
9      Speechiness.      electropop     34